name: Create Release

on:
  workflow_dispatch:
    inputs:
      is_pre:
        description: '發布為測試版'
        type: boolean
      is_draft:
        description: '建立草稿'
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: publish
    env:
      IS_PRE: ${{ github.event.inputs.is_pre }}
      IS_DRAFT: ${{ github.event.inputs.is_draft }}
      TIMEZONE: ${{ vars.TIMEZONE || 'UTC' }}

    # Add explicit permissions for releases
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure and verify
        run: |
          VERSION=$(jq -r '.version' './package.json')
          TAG_NAME="v${VERSION}-$(TZ="$TIMEZONE" date +'%Y%m%d')"

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "RELEASE_NAME=Release ${TAG_NAME}" >> $GITHUB_ENV
          echo "EXT_PATH=NHITW_cloud_analyzer_${TAG_NAME}.zip" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          # Remove the cache option that's causing issues

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Create Git Tag
        run: |
          git tag --force ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Create Zip Archive
        run: |
          cd dist
          zip -r "../${EXT_PATH}" .
          cd ..

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: ${{ env.IS_DRAFT }}
          prerelease: ${{ env.IS_PRE }}
          make_latest: 'legacy'  # 版號較大且非 prelease 時自動標記為 latest
          generate_release_notes: true
          files: ${{ env.EXT_PATH }}
